---
preset: conventionalcommits
branches: main

plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: refactor
          release: patch
        - type: build
          release: patch
        - type: ci
          release: patch
  - - "@semantic-release/release-notes-generator"
    - presetConfig:
        # this overrides the entire `types` property so all the types have to be
        # redefined
        types:
          # default types
          - type: feat
            section: Features
          - type: feature
            section: Features
          - type: fix
            section: Bug Fixes
          - type: perf
            section: Performance Improvements
          - type: revert
            section: Reverts

          # types that were hidden by default
          - type: docs
            section: Documentation
          - type: chore
            section: Miscellaneous Chores
          - type: refactor
            section: Code Refactoring
          - type: test
            section: Tests
          - type: build
            section: Build System
          - type: ci
            section: Continuous Integration
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"
