---
# renovate: datasource=github-releases depName=sharkdp/bat
bat_version: v0.22.1
architecture_to_bat_architecture:
  x86_64: amd64
  armv7l: armhf
bat_architecture: "{{ architecture_to_bat_architecture[ansible_architecture] }}"

# renovate: datasource=github-releases depName=rs/curlie
curlie_version: v1.6.9
architecture_to_curlie_architecture:
  x86_64: amd64
  armv7l: armv6
curlie_architecture:
  "{{ ansible_system | lower }}_\
  {{ architecture_to_curlie_architecture[ansible_architecture] }}"
