---
# renovate: datasource=github-releases depName=sharkdp/bat
bat_version: v0.24.0
architecture_to_bat_architecture:
  x86_64: amd64
  armv7l: armhf
bat_architecture: "{{ architecture_to_bat_architecture[ansible_architecture] }}"

# renovate: datasource=github-releases depName=rs/curlie
curlie_version: v1.7.2
architecture_to_curlie_architecture:
  x86_64: amd64
  armv7l: armv6
curlie_architecture: >-
  {{ architecture_to_curlie_architecture[ansible_architecture] }}

# renovate: datasource=github-releases depName=dandavison/delta
delta_version: 0.18.2
architecture_to_delta_architecture:
  x86_64: amd64
  armv7l: armhf
delta_architecture: >-
  {{ architecture_to_delta_architecture[ansible_architecture] }}

architecture_to_docker_architecture:
  x86_64: amd64
  armv7l: armhf
docker_architecture: >-
  {{ architecture_to_docker_architecture[ansible_architecture] }}
distribution_to_docker_distribution:
  pop!_os: ubuntu
docker_distribution: >-
  {{
  distribution_to_docker_distribution[ansible_distribution | lower]
  | default(ansible_distribution | lower)
  }}

# renovate: datasource=github-releases depName=mr-karan/doggo
doggo_version: v0.5.7
architecture_to_doggo_architecture:
  x86_64: amd64
  armv7l:
doggo_architecture: >-
  {{ architecture_to_doggo_architecture[ansible_architecture] }}

# renovate: datasource=github-releases depName=sharkdp/hyperfine
hyperfine_version: v1.18.0
architecture_to_hyperfine_architecture:
  x86_64: amd64
  armv7l: armhf
hyperfine_architecture: >-
  {{ architecture_to_hyperfine_architecture[ansible_architecture] }}

# renovate: datasource=github-releases depName=jesseduffield/lazydocker
lazydocker_version: v0.23.3
architecture_to_lazydocker_architecture:
  x86_64: x86_64
  armv7l: armv7
lazydocker_architecture: >-
  {{ architecture_to_lazydocker_architecture[ansible_architecture] }}

# renovate: datasource=github-releases depName=jesseduffield/lazygit
lazygit_version: v0.44.1
architecture_to_lazygit_architecture:
  x86_64: x86_64
  armv7l: armv6
lazygit_architecture: >-
  {{ architecture_to_lazygit_architecture[ansible_architecture] }}

# renovate: datasource=github-releases depName=jdx/mise
mise_version: v2024.10.7
architecture_to_mise_architecture:
  x86_64: x64
  armv7l: armv7
mise_architecture: >-
  {{ architecture_to_mise_architecture[ansible_architecture] }}

# renovate: datasource=github-releases depName=ajeetdsouza/zoxide
zoxide_version: v0.9.6
architecture_to_zoxide_architecture:
  x86_64: amd64
  armv7l: armv7
zoxide_architecture: >-
  {{ architecture_to_zoxide_architecture[ansible_architecture] }}
zoxide_architecture_to_zoxide_packaging:
  amd64: deb
  armv7: archive
zoxide_packaging: >-
  {{ zoxide_architecture_to_zoxide_packaging[zoxide_architecture] }}

# By default, this is set to `32`. Some 32bit systems unfortunately do not
# support larger values therefore we set this to `8` on 32bit systems.
# See:
# https://github.com/dev-sec/ansible-collection-hardening/blob/master/roles/os_hardening/README.md#sysctl---vmmmap_rnd_bits
userspace_bits_to_vm_mmap_rnd_bits:
  "32": 8
  "64": 32
vm_mmap_rnd_bits: >-
  {{ userspace_bits_to_vm_mmap_rnd_bits[ansible_userspace_bits] }}
