---
- name: Set plugin names
  ansible.builtin.set_fact:
    asdf_plugins_names: "{{ asdf_plugins | map(attribute='name') | list }}"

- name: Install "direnv" asdf plugin dependencies
  ansible.builtin.package:
    name: direnv
  when: "'direnv' in asdf_plugins_names"

- name: Install "nodejs" asdf plugin dependencies
  ansible.builtin.package:
    name:
      - dirmngr
      - gpg
  when: "'nodejs' in asdf_plugins_names"

# Needed by the python plugin due to pyenv
# See: https://github.com/pyenv/pyenv/wiki#suggested-build-environment
- name: Install "python" asdf plugin dependencies
  ansible.builtin.package:
    name:
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncursesw5-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxmlsec1-dev
      - llvm
      - tk-dev
      - xz-utils
      - zlib1g-dev
  when: "'python' in asdf_plugins_names"

- name: Install "aki" user asdf plugins
  become_user: aki
  ansible.builtin.command:
    cmd: >
      zsh -c "source ~/.asdf/asdf.sh &&
      asdf plugin add {{ item.name }} {{ item.repository | default('') }}"
    creates: ~/.asdf/plugins/{{ item.name }}
  with_items: "{{ asdf_plugins }}"

- name: Install "aki" user asdf tools versions
  become_user: aki
  ansible.builtin.command:
    cmd: >
      zsh -c "source ~/.asdf/asdf.sh &&
      asdf install {{ item.name }} {{ item.version | default('latest') }}"
  register: asdf_install
  retries: 10
  delay: 2
  until: asdf_install is success
  with_items: "{{ asdf_plugins }}"
  changed_when: "'already installed' not in asdf_install.stdout"

- name: Set "aki" user global asdf tools versions
  become_user: aki
  ansible.builtin.command:
    cmd: >
      zsh -c "source ~/.asdf/asdf.sh &&
      asdf global {{ item.name }} {{ item.version | default('latest') }}"
  with_items: "{{ asdf_plugins }}"
  changed_when: false

- name: Setup "aki" user direnv asdf plugin
  become_user: aki
  ansible.builtin.command:
    cmd: >
      zsh -c "source ~/.asdf/asdf.sh &&
      asdf direnv setup --shell zsh --version system"
    creates: ~/.config/asdf-direnv/zshrc
  when: "'direnv' in asdf_plugins_names"

- name: Create "aki" user home directory .envrc
  become_user: aki
  ansible.builtin.command:
    chdir: /home/aki
    cmd: zsh -c "source ~/.asdf/asdf.sh && asdf direnv local"
    creates: ~/.envrc
  when: "'direnv' in asdf_plugins_names"

- name: Discover "aki" user pip executable
  become_user: aki
  ansible.builtin.command:
    cmd: zsh -c "source ~/.asdf/asdf.sh && direnv exec ~ which pip"
  register: which_pip
  changed_when: false
  when: "'python' in asdf_plugins_names"

- name: Set pip executable
  ansible.builtin.set_fact:
    pip_executable: "{{ which_pip.stdout }}"
  when: "'python' in asdf_plugins_names"

- name: Discover "aki" user npm prefix
  become_user: aki
  ansible.builtin.command:
    cmd: >
      zsh -c "source ~/.asdf/asdf.sh && direnv exec ~ npm prefix --global"
  register: npm_prefix_result
  changed_when: false
  when: "'nodejs' in asdf_plugins_names"

- name: Set npm binaries directory
  ansible.builtin.set_fact:
    npm_binaries_dir: "{{ npm_prefix_result.stdout }}/bin"
  when: "'nodejs' in asdf_plugins_names"
