---
- name: Set plugin names
  ansible.builtin.set_fact:
    mise_plugins_names: "{{ mise_plugins | map(attribute='name') | list }}"

- name: Install "nodejs" mise plugin dependencies
  ansible.builtin.package:
    name:
      - dirmngr
      - gpg
  when: "'nodejs' in mise_plugins_names"

# Needed by the python plugin due to pyenv
# See: https://github.com/pyenv/pyenv/wiki#suggested-build-environment
- name: Install "python" mise plugin dependencies
  ansible.builtin.package:
    name:
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncursesw5-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxmlsec1-dev
      - llvm
      - tk-dev
      - xz-utils
      - zlib1g-dev
  when: "'python' in mise_plugins_names"

- name: Install "aki" user mise plugins
  become_user: aki
  ansible.builtin.command:
    cmd: >-
      zsh -c "
      mise use --global --yes
      {{
      mise_plugins |
      map(attribute='name') |
      zip(mise_plugins | map(attribute='version') | map('default', 'latest')) |
      map('join', '@') |
      join(' ')
      }}"
  register: mise_install
  retries: 10
  delay: 2
  until: mise_install is success
  changed_when: "'installed' in mise_install.stdout"

- name: Discover "aki" user pip executable
  become_user: aki
  ansible.builtin.command:
    cmd: zsh -c "mise which pip"
  register: which_pip
  changed_when: false
  when: "'python' in mise_plugins_names"

- name: Set pip executable
  ansible.builtin.set_fact:
    pip_executable: "{{ which_pip.stdout }}"
  when: "'python' in mise_plugins_names"
