---
- name: Create "aki" group
  ansible.builtin.group:
    name: aki

- name: Create "aki" user
  ansible.builtin.user:
    name: aki
    group: aki
    groups: adm,sudo
    append: true
    comment: Aki Kanellis
    password: "{{ aki_password }}"

- name: Copy "aki" user sudoers file
  ansible.builtin.template:
    src: users/aki/sudoer.j2
    dest: /etc/sudoers.d/aki
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s

# TODO sort out dot directories creation location

- name: Create "aki" user home directories
  ansible.builtin.file:
    path: /home/aki/{{ item }}
    state: directory
    owner: aki
    group: aki
    mode: 0700
  loop:
    - .config
    - .config/tilix/schemes
    - .local/bin
    - .local/lib
    - .local/share/applications
    - .local/share/fonts
    - Courses
    - Projects

- name: Install "aki" user fonts
  ansible.builtin.unarchive:
    src:
      "https://github.com/ryanoasis/nerd-fonts/releases/download/\
      {{ nerd_fonts_version }}/\
      Hack.zip"
    dest: /home/aki/.local/share/fonts
    remote_src: true
    owner: aki
    group: aki
    mode: 0600

- name: Setup Tilix
  block:
    - name: Create Tilix default profile
      become_user: aki
      ansible.builtin.dconf:
        key:
          "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/\
          {{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - {key: font, value: "'Hack 14'"}
        - {key: use-system-font, value: "false"}
        - {key: visible-name, value: "'Default'"}

    - name: Set Tilix default profile
      become_user: aki
      ansible.builtin.dconf:
        key: /com/gexperts/Tilix/profiles/default
        value: "'2b7c4080-0ddd-46c5-8f23-563fd3ba789d'"

    - name: Add Tilix One Dark theme
      ansible.builtin.get_url:
        # See: https://github.com/storm119/Tilix-Themes/blob/master/Themes.md
        url: https://git.io/v7Qaw
        dest: /home/aki/.config/tilix/schemes/one-dark.json
        owner: aki
        group: aki
        mode: 0600
