---
- name: Create "aki" group
  ansible.builtin.group:
    name: aki

- name: Create "aki" user
  ansible.builtin.user:
    name: aki
    group: aki
    groups: adm,sudo
    append: true
    comment: Aki Kanellis
    password: "{{ aki_password }}"

- name: Copy "aki" user sudoers file
  ansible.builtin.template:
    src: users/aki/sudoer.j2
    dest: /etc/sudoers.d/aki
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s

- name: Create "aki" user home directories
  ansible.builtin.file:
    path: /home/aki/{{ item }}
    state: directory
    owner: aki
    group: aki
    mode: 0700
  loop:
    - .config
    - .local/bin
    - .local/lib
    - .local/share/applications
    - .local/share/fonts
    - Courses
    - Projects
    - Projects/aki
    - Projects/forks
    - Projects/other

- name: Install "aki" user fonts
  ansible.builtin.unarchive:
    src:
      "https://github.com/ryanoasis/nerd-fonts/releases/download/\
      {{ nerd_fonts_version }}/\
      Hack.zip"
    dest: /home/aki/.local/share/fonts
    include: "*.ttf"
    remote_src: true
    owner: aki
    group: aki
    mode: 0600
