---
- name: Create "aki" group
  ansible.builtin.group:
    name: aki

- name: Create "aki" user
  ansible.builtin.user:
    name: aki
    group: aki
    groups: adm,sudo
    comment: Aki Kanellis
    password: "{{ aki_password }}"
    shell: /bin/bash

- name: Create "aki" user home directories
  ansible.builtin.file:
    path: /home/aki/{{ item }}
    state: directory
    owner: aki
    group: aki
    mode: 0700
  loop:
    - Courses
    - Projects
