---
- name: Install misc tools
  tags: test
  ansible.builtin.package:
    name:
      - caffeine

# TODO pop os time was wrong, maybe need to install ntp

- name: Install Flatpak misc tools
  tags: test
  become_user: aki
  ansible.builtin.flatpak:
    method: user
    name:
      - com.google.Chrome
      - com.slack.Slack
      - com.uploadedlobster.peek
      - org.audacityteam.Audacity
      - org.flameshot.Flameshot
      - org.gimp.GIMP
      - org.kde.kdenlive
      - org.libreoffice.LibreOffice
      - org.mozilla.firefox
      - org.signal.Signal
      - org.videolan.VLC
