---
- name: Install dev tools
  ansible.builtin.package:
    name:
      - perl
      - vagrant

- name: Install asdf dev tools for "aki" user
  ansible.builtin.import_role:
    name: common
    tasks_from: asdf
  vars:
    asdf_plugins:
      - name: java
        version: latest:temurin-18

      - name: kotlin
      - name: groovy
      - name: gradle
      - name: maven
      - name: awscli

- name: Setup git
  block:
    - name: Install lazygit
      ansible.builtin.unarchive:
        src:
          "https://github.com/jesseduffield/lazygit/releases/download/\
          {{ lazygit_version }}/\
          lazygit_\
          {{ lazygit_version | regex_replace('v(.+)', '\\1') }}_\
          Linux_x86_64.tar.gz"
        dest: /home/aki/.local/bin
        include: lazygit
        remote_src: true
        owner: aki
        group: aki

    - name: Copy "aki" user gitconfig
      ansible.builtin.template:
        src: users/aki/gitconfig.j2
        dest: /home/aki/.gitconfig
        owner: aki
        group: aki
        mode: 0600

    - name: Create project directories for "aki" user
      ansible.builtin.file:
        path: /home/aki/Projects/{{ item }}
        state: directory
        owner: aki
        group: aki
        mode: 0700
      loop:
        - aki
        - forks
        - other

- name: Install GitHub CLI
  ansible.builtin.apt:
    deb:
      "https://github.com/cli/cli/releases/download/\
      {{ github_cli_version }}/\
      gh_\
      {{ github_cli_version | regex_replace('v(.+)', '\\1') }}\
      _linux_amd64.deb"

- name: Install Terraform
  block:
    - name: Add HashiCorp apt key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg

    - name: Add HashiCorp apt repository
      ansible.builtin.apt_repository:
        repo: >
          deb
          https://apt.releases.hashicorp.com
          {{ ansible_distribution_release }}
          main

    - name: Install Terraform
      ansible.builtin.package:
        name: terraform

- name: Install python dev tools
  ansible.builtin.import_role:
    name: common
    tasks_from: pip
  vars:
    package_names:
      - ansible
      - molecule
      - yamllint

- name: Install Postman
  become_user: aki
  ansible.builtin.flatpak:
    method: user
    name: com.getpostman.Postman

- name: Install mqtt-explorer
  community.general.snap:
    name: mqtt-explorer

- name: Install just
  community.general.snap:
    name: just
    channel: edge
    classic: true

- name: Install Visual Studio Code and IntelliJ
  community.general.snap:
    classic: true
    name:
      - code
      - intellij-idea-ultimate

- name: Install VirtualBox
  block:
    - name: Add VirtualBox apt key
      ansible.builtin.apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

    - name: Add VirtualBox apt repository
      ansible.builtin.apt_repository:
        repo: >
          deb
          https://download.virtualbox.org/virtualbox/debian
          {{ ansible_distribution_release }}
          contrib

    - name: Accept VirtualBox license
      ansible.builtin.debconf:
        name: virtualbox-ext-pack
        question: virtualbox-ext-pack/license
        value: "true"
        vtype: select

    # VirtualBox needs to be installed before the extensions otherwise the
    # package dependencies will conflict
    - name: Install VirtualBox
      ansible.builtin.package:
        name: virtualbox

    - name: Install VirtualBox extensions
      ansible.builtin.package:
        name:
          - virtualbox-ext-pack
          - virtualbox-guest-utils

- name: Install Wireshark
  block:
    - name: Install Wireshark
      ansible.builtin.package:
        name: wireshark

    - name: Allow non-root users to capture packets with Wireshark
      ansible.builtin.debconf:
        name: wireshark-common
        question: wireshark-common/install-setuid
        value: "true"
        vtype: boolean

    - name: Reconfigure Wireshark
      ansible.builtin.command: >
        dpkg-reconfigure -f noninteractive wireshark-common
      changed_when: false

    - name: Add "aki" user to "wireshark" group
      ansible.builtin.user:
        name: aki
        groups: wireshark
        append: true
