---
- name: Install utilities
  ansible.builtin.package:
    name:
      - arp-scan
      - bash
      - build-essential
      - ca-certificates
      - coreutils
      - cron
      - csvkit
      - curl
      - dialog
      - dnsutils
      - duf
      - exa
      - fzf
      - g++
      - gcc
      - git
      - gnupg
      - hexyl
      - iotop
      - jq
      - libimage-exiftool-perl
      - locate
      - lsb-release
      - make
      - neofetch
      - neovim
      - net-tools
      - nmap
      - p7zip-full
      - pv
      - resolvconf
      - ripgrep
      - tar
      - thefuck
      - traceroute
      - unrar
      - unzip
      - vim
      - wget
      - whois
      - xclip
      - zip

- name: Install bat
  ansible.builtin.apt:
    deb:
      "https://github.com/sharkdp/bat/releases/download/\
      {{ bat_version }}/\
      bat_\
      {{ bat_version | regex_replace('v(.+)', '\\1') }}_\
      amd64.deb"

- name: Install doggo
  ansible.builtin.unarchive:
    src:
      "https://github.com/mr-karan/doggo/releases/download/\
      {{ doggo_version }}/\
      doggo_\
      {{ doggo_version | regex_replace('v(.+)', '\\1') }}_\
      linux_amd64.tar.gz"
    dest: /home/aki/.local/bin
    include: doggo
    remote_src: true
    owner: aki
    group: aki

- name: Install fd
  ansible.builtin.apt:
    deb:
      "https://github.com/sharkdp/fd/releases/download/\
      {{ fd_version }}/\
      fd_\
      {{ fd_version | regex_replace('v(.+)', '\\1') }}_\
      amd64.deb"

- name: Install Snap utilities
  community.general.snap:
    name:
      - btop
      - httpie
      - starship
      - yq

- name: Install zoxide
  ansible.builtin.apt:
    deb:
      "https://github.com/ajeetdsouza/zoxide/releases/download/\
      {{ zoxide_version }}/\
      zoxide_\
      {{ zoxide_version | regex_replace('v(.+)', '\\1') }}_\
      amd64.deb"

- name: Install hyperfine
  ansible.builtin.apt:
    deb:
      "https://github.com/sharkdp/hyperfine/releases/download/\
      {{ hyperfine_version }}/\
      hyperfine_\
      {{ hyperfine_version | regex_replace('v(.+)', '\\1') }}_\
      amd64.deb"

- name: Install curlie
  ansible.builtin.apt:
    deb:
      "https://github.com/rs/curlie/releases/download/\
      {{ curlie_version }}/\
      curlie_\
      {{ curlie_version | regex_replace('v(.+)', '\\1') }}_\
      linux_amd64.deb"

- name: Install delta
  ansible.builtin.apt:
    deb:
      "https://github.com/dandavison/delta/releases/download/\
      {{ delta_version }}/\
      git-delta_\
      {{ delta_version }}_\
      amd64.deb"

- name: Install Docker
  block:
    - name: Add Docker apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }}
          stable

    - name: Install Docker Engine
      ansible.builtin.package:
        name:
          - containerd.io
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin

    - name: Create "docker" group
      ansible.builtin.group:
        name: docker

    - name: Add "aki" user to "docker" group
      ansible.builtin.user:
        name: aki
        groups: docker
        append: true
