---
- name: Install dev tools
  ansible.builtin.apt:
    name:
      - build-essential
      - python3
      - python3-pip
      - python3-virtualenv

- name: Install SDKMAN and packages
  ansible.builtin.import_role:
    name: Comcast.sdkman
  vars:
    sdkman_user: aki
    sdkman_group: aki
    sdkman_auto_answer: true
    sdkman_install_packages:
      - {candidate: java, version: 18.0.1-tem}
      - {candidate: java, version: 17.0.3-tem}
      - {candidate: java, version: 11.0.15-tem}
      - {candidate: java, version: 8.0.332-tem}
      - {candidate: kotlin, version: 1.6.21}
      - {candidate: groovy, version: 4.0.3}
      - {candidate: gradle, version: 7.4.2}
      - {candidate: maven, version: 3.8.5}
    sdkman_defaults:
      java: 18.0.1-tem
    sdkman_flush_caches_before:
      - temp
    sdkman_flush_caches_after:
      - archives
      - broadcast
      - candidates
      - temp
    sdkman_offline_mode: false
    sdkman_update_alternatives:
      - candidate: java
        name: java
        link: /usr/bin/java
      - candidate: java
        name: javac
        link: /usr/bin/javac

- name: Setup git
  block:
    - name: Install git
      ansible.builtin.apt:
        name:
          - git
          - tig

    - name: Copy "aki" user gitconfig
      ansible.builtin.template:
        src: gitconfig-aki.j2
        dest: /home/aki/.gitconfig
        owner: aki
        group: aki
        mode: 0600

    - name: Create project directories for "aki" user
      ansible.builtin.file:
        path: /home/aki/Projects/{{ item }}
        state: directory
        owner: aki
        group: aki
        mode: 0700
      loop:
        - aki
        - forks
        - other

- name: Install jenv
  tags: test
  become_user: aki
  become: true
  community.general.homebrew:
    name: jenv
    path: "/home/aki/.linuxbrew/bin"
