---
- name: Install utilities
  tags: test
  ansible.builtin.package:
    name:
      - arp-scan
      - cron
      - curl
      - dialog
      - dnsutils
      - gnupg
      - htop
      - iotop
      - jq
      - locate
      - neofetch
      - net-tools
      - nmap
      - p7zip-full
      - resolvconf
      - traceroute
      - unrar
      - vim
      - wget
      - whois
      - wireshark-qt
      - xclip
      - zip

- name: Install Snap utilities
  tags: test
  community.general.snap:
    name: yq
