---
- name: Install utilities
  ansible.builtin.package:
    name: dconf-editor

- name: Install git
  block:
    - name: Install lazydocker for "aki" user
      ansible.builtin.unarchive:
        remote_src: true
        src:
          "https://github.com/jesseduffield/lazydocker/releases/download/\
          {{ lazydocker_version }}/\
          lazydocker_\
          {{ lazydocker_version | regex_replace('v(.+)', '\\1') }}_\
          Linux_x86_64.tar.gz"
        dest: /home/aki/.local/bin
        include: lazydocker
        owner: aki
        group: aki
      register: result
      retries: 10
      delay: 2
      until: result is success

- name: Install hyperfine
  ansible.builtin.apt:
    deb:
      "https://github.com/sharkdp/hyperfine/releases/download/\
      {{ hyperfine_version }}/\
      hyperfine_\
      {{ hyperfine_version | regex_replace('v(.+)', '\\1') }}_\
      amd64.deb"
  register: result
  retries: 10
  delay: 2
  until: result is success

- name: Install zoxide
  ansible.builtin.apt:
    deb:
      "https://github.com/ajeetdsouza/zoxide/releases/download/\
      {{ zoxide_version }}/\
      zoxide_\
      {{ zoxide_version | regex_replace('v(.+)', '\\1') }}_\
      amd64.deb"
  register: result
  retries: 10
  delay: 2
  until: result is success
