---
- name: Clone asdf
  become_user: aki
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: v0.10.2 # TODO downgrade for renovate testing
    single_branch: yes
    force: true

- name: Install direnv
  ansible.builtin.import_role:
    name: common
    tasks_from: asdf
  vars:
    asdf_plugins:
      - name: direnv
