---
- name: Install utilities
  ansible.builtin.package:
    name:
      - arp-scan
      - bash
      - build-essential
      - ca-certificates
      - coreutils
      - cron
      - curl
      - dialog
      - dnsutils
      - duf
      - exa
      - fzf
      - g++
      - gcc
      - git
      - gnupg
      - hexyl
      - iotop
      - jq
      - locate
      - lsb-release
      - make
      - neofetch
      - net-tools
      - nmap
      - p7zip-full
      - resolvconf
      - tar
      - thefuck
      - traceroute
      - unrar
      - unzip
      - vim
      - wget
      - whois
      - xclip
      - zip

- name: Install bat
  block:
    - name: Install bat
      ansible.builtin.package:
        name: bat

    - name: Create bat -> batcat symlink
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: /home/aki/.local/bin/bat
        owner: aki
        group: aki
        state: link

- name: Install fd
  block:
    - name: Install fd
      ansible.builtin.package:
        name: fd-find

    - name: Create fd -> fdfind symlink
      ansible.builtin.file:
        src: /usr/bin/fdfind
        dest: /home/aki/.local/bin/fd
        owner: aki
        group: aki
        state: link

- name: Install Snap utilities
  community.general.snap:
    name:
      - btop
      - httpie
      - yq

- name: Install hyperfine
  ansible.builtin.apt:
    deb:
      "https://github.com/sharkdp/hyperfine/releases/download/\
      {{ hyperfine_version }}/\
      hyperfine_\
      {{ hyperfine_version | regex_replace('v(.+)', '\\1') }}_\
      amd64.deb"

- name: Install curlie
  ansible.builtin.apt:
    deb:
      "https://github.com/rs/curlie/releases/download/\
      {{ curlie_version }}/\
      curlie_\
      {{ curlie_version | regex_replace('v(.+)', '\\1') }}_\
      linux_amd64.deb"

- name: Install delta
  ansible.builtin.apt:
    deb:
      "https://github.com/dandavison/delta/releases/download/\
      {{ delta_version }}/\
      git-delta_\
      {{ delta_version }}_\
      amd64.deb"

- name: Install Docker
  tags: test
  block:
    - name: Add Docker apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }}
          stable

    - name: Install Docker Engine
      ansible.builtin.package:
        name:
          - containerd.io
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin

    - name: Create "docker" group
      ansible.builtin.group:
        name: docker

    - name: Add "aki" user to "docker" group
      ansible.builtin.user:
        name: aki
        groups: docker
        append: true
