---
- name: Install dev tools
  ansible.builtin.package:
    name:
      - build-essential
      - perl
      - vagrant

- name: Install asdf dev tools for "aki" user
  # There is currently a bug in cimon-io.asdf where the task setting the global
  # packages always report that it's changed even if it is not. Due to that we
  # need to skip the molecule idempotence test.
  tags: molecule-idempotence-notest
  ansible.builtin.import_role:
    name: cimon-io.asdf
    tasks_from: plugins
  vars:
    asdf_user: aki
    asdf_plugins:
      # Using 'latest:temurin' installs the latest JRE instead of the JDK, so we
      # need to specify the major version
      - name: java
        versions: [latest:temurin-18]
        global: latest:temurin-18

      - name: kotlin
        versions: [latest]
        global: latest

      - name: groovy
        versions: [latest]
        global: latest

      - name: gradle
        versions: [latest]
        global: latest

      - name: maven
        versions: [latest]
        global: latest

      - name: awscli
        versions: [latest]
        global: latest

- name: Setup git
  block:
    - name: Install git
      ansible.builtin.package:
        name:
          - git
          - tig

    - name: Copy "aki" user gitconfig
      ansible.builtin.template:
        src: users/aki/gitconfig.j2
        dest: /home/aki/.gitconfig
        owner: aki
        group: aki
        mode: 0600

    - name: Create project directories for "aki" user
      ansible.builtin.file:
        path: /home/aki/Projects/{{ item }}
        state: directory
        owner: aki
        group: aki
        mode: 0700
      loop:
        - aki
        - forks
        - other

- name: Install GitHub CLI
  tags: test
  block:
    - name: Add GitHub CLI apt key
      ansible.builtin.apt_key:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg

    - name: Add GitHub CLI apt repository
      ansible.builtin.apt_repository:
        repo: deb https://cli.github.com/packages stable main

    - name: Install {{ name }}
      ansible.builtin.package:
        name: gh

- name: Install Terraform
  block:
    - name: Add HashiCorp apt key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg

    - name: Add HashiCorp apt repository
      ansible.builtin.apt_repository:
        repo: >
          deb
          https://apt.releases.hashicorp.com
          {{ ansible_distribution_release }}
          main

    - name: Install Terraform
      ansible.builtin.package:
        name: terraform

- name: Install python dev tools
  ansible.builtin.import_role:
    name: common
    tasks_from: pip
  vars:
    package_names:
      - ansible
      - bpytop
      - molecule
      - pip_search
      - yamllint

- name: Install Flatpak dev tools
  become_user: aki
  ansible.builtin.flatpak:
    method: user
    name: com.getpostman.Postman

- name: Install mqtt-explorer
  community.general.snap:
    name: mqtt-explorer

- name: Install just
  community.general.snap:
    name: just
    channel: edge
    classic: true

- name: Install Snap dev tools with classic confinement
  community.general.snap:
    classic: true
    name:
      - code
      - intellij-idea-ultimate

- name: Install VirtualBox
  block:
    - name: Add VirtualBox apt key
      ansible.builtin.apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

    - name: Add VirtualBox apt repository
      ansible.builtin.apt_repository:
        repo: >
          deb
          https://download.virtualbox.org/virtualbox/debian
          {{ ansible_distribution_release }}
          contrib

    - name: Accept VirtualBox license
      ansible.builtin.debconf:
        name: virtualbox-ext-pack
        question: virtualbox-ext-pack/license
        value: "true"
        vtype: select

    # VirtualBox needs to be installed before the extensions otherwise the
    # package dependencies will conflict
    - name: Install VirtualBox
      ansible.builtin.package:
        name: virtualbox

    - name: Install VirtualBox extensions
      ansible.builtin.package:
        name:
          - virtualbox-ext-pack
          - virtualbox-guest-utils

- name: Install Wireshark
  block:
    - name: Install Wireshark
      ansible.builtin.package:
        name: wireshark

    - name: Allow non-root users to capture packets with Wireshark
      ansible.builtin.debconf:
        name: wireshark-common
        question: wireshark-common/install-setuid
        value: "true"
        vtype: boolean

    - name: Reconfigure Wireshark
      ansible.builtin.command: >
        dpkg-reconfigure -f noninteractive wireshark-common
      changed_when: false

    - name: Add "aki" user to "wireshark" group
      ansible.builtin.user:
        name: aki
        groups: wireshark
        append: true

- name: Install Docker
  block:
    - name: Add Docker apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }}
          stable

    - name: Install Docker Engine
      ansible.builtin.package:
        name:
          - containerd.io
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin

    - name: Create "docker" group
      ansible.builtin.group:
        name: docker

    - name: Add "aki" user to "docker" group
      ansible.builtin.user:
        name: aki
        groups: docker
        append: true
