---
- name: Install utilities
  ansible.builtin.package:
    name:
      - arp-scan
      - cron
      - curl
      - dialog
      - dnsutils
      - gnupg
      - htop
      - iotop
      - locate
      - neofetch
      - net-tools
      - nmap
      - p7zip-full
      - resolvconf
      - traceroute
      - unrar
      - vim
      - wget
      - whois
      - wireshark-qt
      - xclip
      - zip
