---
- name: Install misc tools
  tags: test
  ansible.builtin.package:
    name:
      - asunder
      - audacity
      - caffeine
      - cups
      - flameshot
      - gimp
      - gparted

- name: Install Snap misc tools
  tags: test
  ansible.builtin.snap:
    name:
      - slack
      - vlc
