---
- name: Install utilities
  ansible.builtin.package:
    name:
      - arp-scan
      - bash
      - build-essential
      - ca-certificates
      - cron
      - curl
      - dialog
      - dnsutils
      - g++
      - gcc
      - git
      - gnupg
      - iotop
      - jq
      - locate
      - lsb-release
      - make
      - neofetch
      - net-tools
      - nmap
      - p7zip-full
      - resolvconf
      - tar
      - traceroute
      - unrar
      - unzip
      - vim
      - wget
      - whois
      - xclip
      - zip

- name: Install yq
  community.general.snap:
    name: yq

# TODO integrate renovate
- name: Install hyperfine
  ansible.builtin.apt:
    deb: >-
      https://github.com/sharkdp/hyperfine/releases/download/v1.14.0/hyperfine_1.14.0_amd64.deb
