---
- name: Install misc tools
  tags: test
  ansible.builtin.package:
    name:
      - caffeine

# TODO pop os time was wrong, maybe need to install ntp

- name: Install Flatpak misc tools
  tags: test
  become_user: aki
  ansible.builtin.flatpak:
    method: user
    name:
      - org.audacityteam.Audacity
      - org.flameshot.Flameshot
      - org.gimp.GIMP
      - org.libreoffice.LibreOffice
      - org.signal.Signal
      - com.slack.Slack
      - org.videolan.VLC
