---
- name: Install utilities
  ansible.builtin.package:
    name:
      - arp-scan
      - cron
      - curl
      - dnsutils
      - gnupg
      - htop
      - iotop
      - locate
      - neofetch
      - net-tools
      - nmap
      - resolvconf
      - traceroute
      - vim
      - wget
      - whois
      - wireshark-qt
      - xclip
