---
- name: Install package management tools
  ansible.builtin.apt:
    name:
      - aptitude
      - flatpak
      - snapd
      - software-properties-common

- name: Add the flathub flatpak repository remote for "aki" user
  become_user: aki
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install Homebrew
  ansible.builtin.import_role:
    name: monolithprojects.homebrew
    tasks_from: install
  vars:
    homebrew_user: aki

- name: Install SDKMAN!
  ansible.builtin.import_role:
    name: Comcast.sdkman
    tasks_from: install
  vars:
    sdkman_user: aki
    sdkman_group: aki
    sdkman_dir: /home/aki/.sdkman
    sdkman_auto_answer: true
    sdkman_auto_selfupdate: true

- name: Install pip
  ansible.builtin.package:
    name:
      - python3-pip
