---
- name: Install asdf plugins
  tags: test
  ansible.builtin.import_role:
    name: common
    tasks_from: asdf
  vars:
    asdf_plugins:
      - name: lazydocker
        repository: https://github.com/comdotlinux/asdf-lazydocker.git

      - name: nodejs

      - name: python

- name: Install tldr
  tags: test
  ansible.builtin.import_role:
    name: common
    tasks_from: npm
  vars:
    package_names: [tldr]

- name: Install pip_search
  ansible.builtin.import_role:
    name: common
    tasks_from: pip
  vars:
    package_names: pip_search
