---
- name: Install utilities
  ansible.builtin.package:
    name:
      - arp-scan
      - bash
      - build-essential
      - ca-certificates
      - coreutils
      - cron
      - curl
      - dialog
      - dnsutils
      - g++
      - gcc
      - git
      - gnupg
      - iotop
      - jq
      - locate
      - lsb-release
      - make
      - neofetch
      - net-tools
      - nmap
      - p7zip-full
      - resolvconf
      - tar
      - traceroute
      - unrar
      - unzip
      - vim
      - wget
      - whois
      - xclip
      - zip

- name: Install bat
  tags: test
  block:
    - name: Install bat
      ansible.builtin.package:
        name: bat

    - name: Create bat -> batcat symlink
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: /home/aki/.local/bin/bat
        owner: aki
        group: aki
        state: link

- name: Install Snap utilities
  community.general.snap:
    name:
      - btop
      - yq

- name: Install hyperfine
  ansible.builtin.apt:
    deb:
      "https://github.com/sharkdp/hyperfine/releases/download/\
      {{ hyperfine_version }}/\
      hyperfine_\
      {{ hyperfine_version | regex_replace('v(.+)', '\\1') }}\
      _amd64.deb"

- name: Install curlie
  ansible.builtin.apt:
    deb:
      "https://github.com/rs/curlie/releases/download/\
      {{ curlie_version }}/\
      curlie_\
      {{ curlie_version | regex_replace('v(.+)', '\\1') }}\
      _linux_amd64.deb"
