---
- name: Install dev tools
  ansible.builtin.apt:
    name:
      - build-essential
      - git
      - tig
      - python3
      - python3-pip
      - python3-virtualenv

- name: Install SDKMAN and packages
  tags: test
  import_role:
    name: Comcast.sdkman
  vars:
    sdkman_user: aki
    sdkman_group: aki
    sdkman_auto_answer: true
    sdkman_install_packages:
      - {candidate: java, version: 18.0.1-tem}
      - {candidate: java, version: 17.0.3-tem}
      - {candidate: java, version: 11.0.15-tem}
      - {candidate: java, version: 8.0.332-tem}
      - {candidate: kotlin, version: 1.6.21}
      - {candidate: groovy, version: 4.0.3}
      - {candidate: gradle, version: 7.4.2}
      - {candidate: maven, version: 3.8.5}
    sdkman_defaults:
      java: 18.0.1-tem
    sdkman_flush_caches_before:
      - temp
    sdkman_flush_caches_after:
      - archives
      - broadcast
      - candidates
      - temp
    sdkman_offline_mode: false
    sdkman_update_alternatives:
      - candidate: java
        name: java
        link: /usr/bin/java
      - candidate: java
        name: javac
        link: /usr/bin/javac
