---
- name: Install package management tools
  ansible.builtin.package:
    name:
      - aptitude
      - flatpak
      - snapd
      - software-properties-common

- name: Add the flathub flatpak repository remote for "aki" user
  become_user: aki
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install Homebrew for "aki" user
  ansible.builtin.import_role:
    name: monolithprojects.homebrew
    tasks_from: install
  vars:
    homebrew_user: aki

- name: Install SDKMAN! for "aki" user
  ansible.builtin.import_role:
    name: common
    tasks_from: sdkman

- name: Install pip
  ansible.builtin.package:
    name: python3-pip

- name: Install Node Version Manager for "aki" user
  ansible.builtin.import_role:
    name: monolithprojects.homebrew
    tasks_from: formulae
  vars:
    homebrew_user: aki
    brew_formulae: nvm
