---
- name: Install package management tools
  ansible.builtin.apt:
    name:
      - aptitude
      - flatpak
      - snapd
      - software-properties-common

- name: Add the flathub flatpak repository remote for "aki" user
  become_user: aki
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install homebrew
  tags: test
  ansible.builtin.import_role:
    name: monolithprojects.homebrew
  vars:
    homebrew_user: aki
  notify: update-brew
