---
- ansible.builtin.import_tasks: create-aki-user.yml
- ansible.builtin.import_tasks: install-package-managers.yml
- ansible.builtin.import_tasks: setup-time.yml
- ansible.builtin.import_tasks: remove-preinstalled-packages.yml
- ansible.builtin.import_tasks: install-utilities.yml
- ansible.builtin.import_tasks: setup-ssh.yml
- ansible.builtin.import_tasks: setup-zsh.yml
- ansible.builtin.import_tasks: install-asdf.yml
- ansible.builtin.import_tasks: install-asdf-utilities.yml
- ansible.builtin.import_tasks: install-dev-tools.yml
- ansible.builtin.import_tasks: install-misc-tools.yml
