---
- name: Update package cache
  tags: always
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- ansible.builtin.import_tasks: setup-ansible.yml
- ansible.builtin.import_tasks: create-aki-user.yml
- ansible.builtin.import_tasks: install-package-management-tools.yml
- ansible.builtin.import_tasks: install-utilities.yml
- ansible.builtin.import_tasks: install-dev-tools.yml
- ansible.builtin.import_tasks: setup-ssh.yml
- ansible.builtin.import_tasks: setup-zsh.yml

- name: Clean package cache
  tags: always
  ansible.builtin.apt:
    autoclean: true

- name: Remove orphan packages
  tags: always
  ansible.builtin.apt:
    autoremove: true
    purge: true
