---
# TODO state
- name: Setup passwordless sudo
  tags: initial-setup
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: ^%sudo
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s

- name: Create "ansible" user
  tags: initial-setup
  ansible.builtin.user:
    name: ansible
    groups: sudo
    append: true

- name: Set authorized key for "ansible" user
  tags: initial-setup
  ansible.posix.authorized_key:
    user: ansible
    key: "{{ lookup('file', 'files/ssh/id_ansible.pub') }}"

- import_tasks: create-aki-user.yml

- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

