---
- name: Install utilities
  ansible.builtin.import_tasks: install-utilities.yml

- name: Setup SSH
  ansible.builtin.import_tasks: setup-ssh.yml

- name: Setup ZSH
  ansible.builtin.import_tasks: setup-zsh.yml

- name: Install dev tools
  ansible.builtin.import_tasks: install-dev-tools.yml

- name: Install misc tools
  ansible.builtin.import_tasks: install-misc-tools.yml

- name: Tweak settings
  ansible.builtin.import_tasks: tweak-settings.yml
