---
- name: Setup ZSH
  ansible.builtin.import_role:
    name: gantsign.antigen
  vars:
    users:
      - username: aki
        antigen_libraries:
          - name: oh-my-zsh
        antigen_theme:
          name: robbyrussell
        antigen_bundles:
          - name: git

- name: Create "aki" user ZSH directories
  ansible.builtin.file:
    path: /home/aki/.zsh
    state: directory
    owner: aki
    group: aki
    mode: 0700

- name: Copy "aki" user ZSH configs
  ansible.builtin.template:
    src: zsh/{{ item }}.j2
    dest: /home/aki/.zsh/{{ item }}.zsh
    owner: aki
    group: aki
    mode: 0600
  loop:
    - path
    - sdkman
    - terraform

- name: Copy "aki" user zshenv
  ansible.builtin.template:
    src: zsh/zshenv.j2
    dest: /home/aki/.zshenv
    owner: aki
    group: aki
    mode: 0600

- name: Copy "aki" user zshrc
  ansible.builtin.template:
    src: zsh/zshrc.j2
    dest: /home/aki/.zshrc
    owner: aki
    group: aki
    # This needs to match the mode set by gantsign.antigen
    mode: 0644
