---
- name: Setup SSH
  ansible.builtin.import_role:
    name: devsec.hardening.ssh_hardening
  vars:
    ssh_allow_users: "{{ ansible_user }} aki"

- name: Ensure .ssh directory exists for "aki" user
  file:
    path: /home/aki/.ssh
    state: directory
    owner: aki
    group: aki
    mode: 0700

- name: Copy "aki" user ssh keys
  copy:
    src: "{{ item.src }}"
    dest: /home/aki/.ssh/{{ item.dest }}
    owner: aki
    group: aki
    mode: 0600
  loop:
    - { src: "{{ aki_ssh_private_key_file }}", dest: id_ed25519_aki.pk }
    - { src: "{{ aki_ssh_public_key_file }}", dest: id_ed25519_aki.pub }

- name: Copy "aki" user ssh client config
  copy:
    src: ssh/config-aki.txt
    dest: /home/aki/.ssh/config
    owner: aki
    group: aki
    mode: 0600
