---
- name: Setup ZSH
  ansible.builtin.import_role:
    name: gantsign.antigen
  vars:
    users:
      - username: aki
        antigen_libraries:
          - name: oh-my-zsh
        antigen_theme:
          name: robbyrussell
        antigen_bundles:
          - name: git
