---
- name: Setup passwordless sudo
  tags: ansible-setup
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: ^%sudo
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s

- name: Create "ansible" user
  tags: ansible-setup
  ansible.builtin.user:
    name: ansible
    groups: sudo
    append: true

- name: Set authorized key for "ansible" user
  tags: ansible-setup
  ansible.posix.authorized_key:
    user: ansible
    key: "{{ lookup('file', 'files/ssh/id_ansible.pub') }}"
