vars: {
  d2-config: {
    layout-engine: elk
    theme-id: 200
  }
}

direction: down

classes: {
  # # Groups

  room: { style: { stroke-dash: 10 } }
  area: { style: { stroke-dash: 5 } }

  # # Nodes

  device: {
    shape: image
    height: 200
    width: 200
  }
  long-device: {
    shape: image
    height: 100
    width: 400
  }
  apc-be850g2-uk: {
    label: UPS\nAPC BackUPS 850 (520W, 8 outlets)
    icon: ../images/apc_be850g2_uk.svg
    shape: image
    height: 200
    width: 200
  }
  ubiquiti-flex-mini-2_5g: {
    label: Switch\nUbiquiti Flex Mini 2.5G
    icon: ../images/ubiquiti_usw_flex_2.5g_5.svg
    shape: image
    height: 200
    width: 200
  }
  ubiquiti-g5-flex: {
    label: Camera\nUbiquiti G5 Flex
    icon: ../images/ubiquiti_uvc_g5_flex.svg
    shape: image
    height: 200
    width: 200
  }

  # # Connections

  # ## Power

  power-mains: { style: { stroke: crimson } }
  surge-protected: { label: 🛡️ }
  surge-and-battery-protected: { label: 🛡️+🔋 }

  # ## Network

  # ### Wired
  cat6-any: { style: { stroke: ghostwhite } }
  cat6-100mb: { style: { stroke: orange } }
  cat6-1gbe: { style: { stroke: limegreen } }
  cat6-2_5gbe: { style: { stroke: fuchsia } }

  poe: { label: ⚡ }
  poe+: { label: ⚡➕ }
  poe++: { label: ⚡➕➕ }

  sfp+-10gbe: { style: { stroke: turquoise } }

  # ### Wireless

  wifi7: { style: { stroke-dash: 4 } }

  # ## Misc

  kvm: { label: Video + USB; style: { stroke: black } }
  ups: { label: RJ11 to USB; style: { stroke: black } }
}

internet: {
  class: device
  label: Internet\n750mbps Symmetrical Speed
  icon: ../images/internet.svg
}

mains-power: {
  class: device
  label: Mains Power
  icon: ../images/mains_power.svg
}

corridor: {
  class: room
  label: Corridor
  icon: ../images/corridor.svg

  isp-termination: {
    class: device
    label: ISP Termination
    icon: ../images/rj45_wall_plate.svg
  }

  camera: { class: ubiquiti-g5-flex }
}

office: {
  class: room
  label: Office
  icon: ../images/office.svg

  server-rack: {
    class: area
    label: Server Rack

    ups: { class: apc-be850g2-uk }
    pdu: {
      class: long-device
      label: PDU
      icon: ../images/pdu.svg
    }

    router: {
      class: long-device
      label: Router\nUbiquiti Dream Machine Pro Max
      icon: ../images/ubiquiti_udm_pro_max.svg
    }
    switch: {
      class: long-device
      label: Switch\nUbiquiti Pro Max 24 PoE
      icon: ../images/ubiquiti_usw_pro_max_24_poe.svg
    }
    patch-panel: {
      class: long-device
      label: Patch Panel\nUbiquiti 24-Blank Keystone Patch Panel
      icon: ../images/ubiquiti_uacc_rack_panel_patch_blank_24.svg
    }

    host-kvm: {
      class: device
      label: Host\nKVM\nBlicube BliKVM v4 Allwinner
      icon: ../images/blicube_blikvm_v4_allwinner.svg
    }
    host-nas: {
      class: device
      label: Host\nNAS\nSynology DS218+
      icon: ../images/synology_ds218+.svg
    }
    host-hypervisor: {
      class: device
      label: Host\nHypervisor\nHP ProDesk 400 G6 Desktop Mini PC
      icon: ../images/hp_prodesk_400_g6_desktop_mini_pc.svg
    }
  }

  desk: {
    class: area
    label: Desk
    icon: ../images/desk.svg

    surge_protection: {
      class: device
      label: Surge Protection\nBelkin SurgeCube 1 Way
      icon: ../images/belkin_bsv102af.svg
    }
    extension_lead: {
      class: long-device
      label: Extension Lead\nBrennenstuhl Premium-Line 12 Way
      icon: ../images/brennenstuhl_premium_line_12_way_extension_lead.svg
    }

    switch: { class: ubiquiti-flex-mini-2_5g }

    workstation-pc: {
      class: device
      label: Workstation\nPC
      icon: ../images/fractal_design_define_r6_tg.svg
    }
    workstation-work-laptop: {
      class: device
      label: Workstation\nWork Laptop
      icon: ../images/apple_macbook_pro.svg
    }
  }

  surge_protection: {
    class: long-device
    label: Surge Protection\nBelkin Extension Lead 8 Way
    icon: ../images/belkin_bsv804.svg
  }

  ap: {
    class: device
    label: Access Point\nUbiquiti U7 Pro Max
    icon: ../images/ubiquiti_u7_pro_max.svg
  }
  camera: { class: ubiquiti-g5-flex }
  printer: {
    class: device
    label: Printer\nHP Colour LaserJet Pro M283FDW
    icon: ../images/hp_colour_laserjet_pro_m283fdw.svg
  }
  label-printer: {
    class: device
    label: Printer\nBrother QL-820NWB Label Printer
    icon: ../images/brother_ql_820nwb.svg
  }
}

lounge: {
  class: room
  label: Lounge
  icon: ../images/lounge.svg

  ups: { class: apc-be850g2-uk }

  switch: { class: ubiquiti-flex-mini-2_5g }
  poe-adapter: {
    class: device
    label: PoE Adapter\nUbiquiti PoE Adapter (15W)
    icon: ../images/ubiquiti_u_poe_af.svg
  }
  camera: { class: ubiquiti-g5-flex }

  shield: {
    class: device
    label: NVIDIA SHIELD
    icon: ../images/nvidia_shield_tv_2017.svg
  }
  ps5: {
    class: device
    label: Playstation 5 Slim
    icon: ../images/sony_ps5_slim.svg
  }
}

# # Connections

# ## Mains Power

# ### Office

# #### Server Rack

mains-power -- office.server-rack.ups: {class: power-mains}

office.server-rack.ups -- office.server-rack.pdu: {class: [power-mains; surge-and-battery-protected]}

office.server-rack.pdu -- office.server-rack.router: {class: [power-mains; surge-and-battery-protected]}
office.server-rack.pdu -- office.server-rack.switch: {class: [power-mains; surge-and-battery-protected]}
office.server-rack.pdu -- office.server-rack.host-nas: {class: [power-mains; surge-and-battery-protected]}
office.server-rack.pdu -- office.server-rack.host-hypervisor: {class: [power-mains; surge-and-battery-protected]}

# #### Desk

mains-power -- office.desk.surge_protection: {class: power-mains}

office.desk.surge_protection -- office.desk.extension_lead: {class: [power-mains; surge-protected]}

office.desk.extension_lead -- office.desk.workstation-pc: {class: [power-mains; surge-protected]}
office.desk.extension_lead -- office.desk.workstation-work-laptop: {class: [power-mains; surge-protected]}

# #### Other

mains-power -- office.surge_protection: {class: power-mains}

office.surge_protection -- office.printer: {class: [power-mains; surge-protected]}
office.surge_protection -- office.label-printer: {class: [power-mains; surge-protected]}

# ### Lounge

# #### Other

mains-power -- lounge.ups: {class: power-mains}

lounge.ups -- lounge.poe-adapter: {class: [power-mains; surge-and-battery-protected]}
lounge.ups -- lounge.shield: {class: [power-mains; surge-and-battery-protected]}
lounge.ups -- lounge.ps5: {class: [power-mains; surge-and-battery-protected]}

# ## Network

# ### Corridor

internet -- corridor.isp-termination: { class: cat6-any }

# ### Office

# #### Server Rack

corridor.isp-termination -- office.server-rack.router: {
  class: cat6-any
  target-arrowhead: 9
}

office.server-rack.router -- office.server-rack.switch: {
  class: sfp+-10gbe
  source-arrowhead: 11
  target-arrowhead: 26
}

office.server-rack.switch -- office.server-rack.patch-panel: { class: cat6-any }

office.server-rack.patch-panel -- office.desk.switch: {
  class: [cat6-2_5gbe; poe]
  source-arrowhead: 24
  target-arrowhead: 5
}
office.server-rack.patch-panel -- lounge.switch: {
  class: [cat6-2_5gbe; poe]
  source-arrowhead: 23
  target-arrowhead: 5
}
office.server-rack.patch-panel -- corridor.camera: {
  class: [cat6-100mb; poe]
  source-arrowhead: 1
}
office.server-rack.patch-panel -- office.ap: {
  class: [cat6-2_5gbe; poe+]
  source-arrowhead: 22
}
office.server-rack.patch-panel -- office.camera: {
  class: [cat6-100mb; poe]
  source-arrowhead: 2
}
office.server-rack.patch-panel -- office.server-rack.host-kvm: {
  class: [cat6-1gbe; poe]
  source-arrowhead: 3
}
office.server-rack.patch-panel -- office.server-rack.host-hypervisor: {
  class: cat6-2_5gbe
  source-arrowhead: 21
}
office.server-rack.patch-panel -- office.server-rack.host-nas: {
  class: cat6-2_5gbe
  source-arrowhead: 20
}
office.server-rack.patch-panel -- office.printer: {
  class: cat6-1gbe
  source-arrowhead: 4
}
office.server-rack.patch-panel -- office.label-printer: {
  class: cat6-100mb
  source-arrowhead: 5
}

# #### Desk

office.desk.switch -- office.desk.workstation-pc: {
  class: cat6-2_5gbe
  source-arrowhead: 1
}
office.desk.switch -- office.desk.workstation-work-laptop: {
  class: cat6-2_5gbe
  source-arrowhead: 2
}

# ### Lounge

# #### Other

lounge.switch -- lounge.poe-adapter: {
  class: cat6-100mb
  source-arrowhead: 1
}
lounge.switch -- lounge.shield: {
  class: cat6-2_5gbe
  source-arrowhead: 2
}
lounge.switch -- lounge.ps5: {
  class: cat6-1gbe
  source-arrowhead: 3
}

lounge.poe-adapter -- lounge.camera: {class: [cat6-100mb; poe]}

# ## Other

office.server-rack.ups -- office.server-rack.host-hypervisor: { class: ups }
office.server-rack.host-kvm -- office.server-rack.host-hypervisor: { class: kvm }
