---
# This needs to be disabled because it causes a port conflict with pihole on
# port 53.
# See: https://github.com/pi-hole/docker-pi-hole#installing-on-ubuntu-or-fedora
- name: Disable DNS stub listener
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: ^#DNSStubListener=
    line: DNSStubListener=no
  register: disable_dns_stub_listener_result

- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  when: disable_dns_stub_listener_result.changed
