---
# This needs to be disabled because it causes a port conflict with pihole on
# port 53.
# See: https://github.com/pi-hole/docker-pi-hole#installing-on-ubuntu-or-fedora
- name: Disable DNS stub listener
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: ^#DNSStubListener=
    line: DNSStubListener=no
  notify:
    - Restart systemd-resolved
    - Restart docker

- name: Create `/etc/resolv.conf -> /run/systemd/resolve/resolv.conf` symlink
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
  notify:
    - Restart systemd-resolved
    - Restart docker

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
