---
- name: Check if pip path exists
  stat:
    path: /usr/bin/pip
  register: pip_path

- name: Clean pip
  ansible.builtin.shell:
    cmd: pip cache purge
  register: pip_clean
  changed_when: "pip_clean.stdout not in 'Files removed: 0'"
  when: pip_path.stat.exists
