---
- name: Check if SDKMAN! path exists
  stat:
    path: /home/aki/.sdkman
  register: sdkman_path

- name: Clean SDKMAN!
  become_user: aki
  ansible.builtin.import_role:
    name: Comcast.sdkman
    tasks_from: sdkman
  vars:
    sdkman_user: aki
    sdkman_group: aki
    sdkman_dir: /home/aki/.sdkman
    sdkman_auto_answer: true
    sdkman_auto_selfupdate: true
    sdkman_flush_caches_after:
      - archives
      - broadcast
      - candidates
      - metadata
      - tmp
      - version
  when: sdkman_path.stat.exists
