---
- name: Check if pip path exists
  stat:
    path: /usr/bin/pip
  register: pip_path

- name: Clean pip
  ansible.builtin.shell:
    cmd: pip cache purge
  register: pip_clean
  changed_when: "'Files removed: 0' not in pip_clean.stdout"
  when: pip_path.stat.exists
