---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: vagrant

platforms:
  - name: workstation-pop-os
    box: ubuntu/focal64

provisioner:
  name: ansible

verifier:
  name: ansible
