---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml

driver:
  name: vagrant

platforms:
  - name: workstation-pop-os
    groups: [workstations]
    box: ubuntu/focal64

provisioner:
  name: ansible
  config_options:
    defaults:
      vault_password_file: |
        ${MOLECULE_SCENARIO_DIRECTORY}/../../vault-password-dev.txt
  inventory:
    links:
      group_vars: ../../inventories/dev/group_vars/

verifier:
  name: ansible
