---
- name: Update All Hosts Package Cache
  hosts: all
  tags: always
  become: true

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - ansible.builtin.import_tasks: tasks/update-homebrew.yml
    - ansible.builtin.import_tasks: tasks/update-sdkman.yml

- name: Apply All Hosts Configuration
  hosts: all
  become: true

  roles: [all]

- name: Apply Workstations Configuration
  hosts: workstations
  become: true

  roles: [workstations]

- name: Cleanup All Hosts
  hosts: all
  tags: always
  become: true

  tasks:
    - name: Clean package cache
      ansible.builtin.apt:
        autoclean: true

    - name: Remove orphan packages
      ansible.builtin.apt:
        autoremove: true
        purge: true

    - ansible.builtin.import_tasks: tasks/clean-homebrew.yml
    - ansible.builtin.import_tasks: tasks/clean-pip.yml
    - ansible.builtin.import_tasks: tasks/clean-sdkman.yml
