---
- name: Bootstrap All for Ansible
  hosts: all
  become: true
  gather_facts: false

  roles: [robertdebock.bootstrap]

- name: Apply Workstations Configuration
  hosts: workstations
  become: true

  roles: [workstations]
