---
- name: Apply Configuration
  hosts: all
  become: true

  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
