---
- name: Update All Managed Hosts Package Caches
  hosts:
    - all
    - "!unmanaged"
  tags: always
  become: true

  tasks:
    - name: Update apt
      ansible.builtin.import_tasks: tasks/update-apt.yml

- name: Apply All Managed Hosts Configuration
  hosts:
    - all
    - "!unmanaged"
  become: true

  roles: [all]

- name: Apply Workstations Configuration
  hosts: workstations
  become: true

  roles: [workstations]

- name: Apply Managed Servers Configuration
  hosts:
    - servers
    - "!unmanaged"
  become: true

  roles: [servers_managed]

- name: Apply Servers Configuration
  hosts: servers
  become: true

  roles: [servers]

- name: Cleanup All Managed Hosts
  hosts:
    - all
    - "!unmanaged"
  tags: always
  become: true

  tasks:
    - name: Clean apt
      ansible.builtin.import_tasks: tasks/clean-apt.yml
