---
- name: Update All Hosts Package Caches
  hosts: all
  tags: always
  become: true

  tasks:
    - name: Update apt
      ansible.builtin.import_tasks: tasks/update-apt.yml

- name: Apply All Hosts Configuration
  hosts: all
  become: true

  roles: [all]

- name: Apply Workstations Configuration
  hosts: workstations
  become: true

  roles: [workstations]

- name: Apply Servers Configuration
  hosts: servers
  become: true

  roles: [servers]

- name: Cleanup All Hosts
  hosts: all
  tags: always
  become: true

  tasks:
    - name: Clean apt
      ansible.builtin.import_tasks: tasks/clean-apt.yml
