---
- name: Update All Hosts Package Caches
  hosts: all
  tags: always
  become: true

  tasks:
    - ansible.builtin.import_tasks: tasks/update-apt.yml
    - ansible.builtin.import_tasks: tasks/update-homebrew.yml
    - ansible.builtin.import_tasks: tasks/update-sdkman.yml

- name: Apply All Hosts Configuration
  hosts: all
  become: true

  roles: [all]

- name: Apply Workstations Configuration
  hosts: workstations
  become: true

  roles: [workstations]

- name: Cleanup All Hosts
  hosts: all
  tags: always
  become: true

  tasks:
    - ansible.builtin.import_tasks: tasks/clean-apt.yml
    - ansible.builtin.import_tasks: tasks/clean-homebrew.yml
    - ansible.builtin.import_tasks: tasks/clean-pip.yml
    - ansible.builtin.import_tasks: tasks/clean-sdkman.yml
