---
- name: Perform Initial Setup
  hosts: all
  become: true

  tasks:
    - name: Setup passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: ^%sudo
        line: "%sudo ALL=(ALL) NOPASSWD: ALL"
        validate: visudo -cf %s

    - name: Create "ansible" user
      ansible.builtin.user:
        name: ansible
        groups: sudo
        append: true

    - name: Set authorized key for "ansible" user
      ansible.posix.authorized_key:
        user: ansible
        key: "{{ lookup('file', 'files/ssh/id_ansible.pub') }}"
