---
- name: Create "aki" group
  ansible.builtin.group:
    name: aki

- name: Create "aki" user
  ansible.builtin.user:
    name: aki
    group: aki
    groups: adm,sudo
    append: true
    comment: Aki Kanellis
    password: "{{ aki_password }}"

- name: Copy "aki" user sudoers file
  ansible.builtin.template:
    src: users/aki/sudoer.j2
    dest: /etc/sudoers.d/aki
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s

- name: Create "aki" user home directories
  ansible.builtin.file:
    path: /home/aki/{{ item }}
    state: directory
    owner: aki
    group: aki
    mode: 0700
  loop: "{{ aki_user_home_directories }}"
  vars:
    aki_user_base_home_directories:
      - .config
      - .local/bin
      - .local/lib
      - .local/share/applications
      - .local/share/fonts
    aki_user_home_directories: >
      {{
      aki_user_base_home_directories +
      aki_user_additional_home_directories
      }}
