---
- name: Install utilities
  ansible.builtin.package:
    name:
      - arp-scan
      - bash
      - build-essential
      - ca-certificates
      - coreutils
      - cron
      - csvkit
      - curl
      - dconf-cli
      - dialog
      - dnsutils
      - duf
      - exa
      - fzf
      - g++
      - gcc
      - gnupg
      - hexyl
      - iotop
      - jq
      - libimage-exiftool-perl
      - locate
      - lsb-release
      - make
      - neofetch
      - neovim
      - net-tools
      - nmap
      - p7zip-full
      - pv
      - resolvconf
      - ripgrep
      - tar
      - thefuck
      - traceroute
      - unrar
      - unzip
      - vim
      - wget
      - whois
      - xclip
      - zip

- name: Install Snap utilities
  community.general.snap:
    name:
      - btop
      - httpie
      - starship
      - yq
