---
- name: Install mise plugins
  ansible.builtin.import_role:
    name: common
    tasks_from: mise
  vars:
    mise_plugins:
      - name: nodejs
      - name: python

- name: Install Node utilities
  ansible.builtin.import_role:
    name: common
    tasks_from: npm
  vars:
    package_names: [tldr]

- name: Install Python utilities
  ansible.builtin.import_role:
    name: common
    tasks_from: pip
  vars:
    package_names: [pip_search]
