---
- name: Install asdf plugins
  ansible.builtin.import_role:
    name: common
    tasks_from: asdf
  vars:
    asdf_plugins:
      - name: nodejs
      - name: python

- name: Install tldr
  ansible.builtin.import_role:
    name: common
    tasks_from: npm
  vars:
    package_names: [tldr]

- name: Install pip_search
  ansible.builtin.import_role:
    name: common
    tasks_from: pip
  vars:
    package_names: pip_search
