---
- ansible.builtin.import_tasks: setup-ansible.yml
- ansible.builtin.import_tasks: create-aki-user.yml
- ansible.builtin.import_tasks: install-package-managers.yml
- ansible.builtin.import_tasks: setup-time.yml
- ansible.builtin.import_tasks: setup-ssh.yml
