---
- name: Setup ansible
  ansible.builtin.import_tasks: setup-ansible.yml

- name: Create aki user
  ansible.builtin.import_tasks: create-aki-user.yml

- name: Install package managers
  ansible.builtin.import_tasks: install-package-managers.yml

- name: Setup time
  ansible.builtin.import_tasks: setup-time.yml

- name: Remove preinstalled packages
  ansible.builtin.import_tasks: remove-preinstalled-packages.yml

- name: Install utilities
  ansible.builtin.import_tasks: install-utilities.yml

- name: Setup OS
  ansible.builtin.import_tasks: setup-os.yml

- name: Setup SSH
  ansible.builtin.import_tasks: setup-ssh.yml

- name: Setup ZSH
  ansible.builtin.import_tasks: setup-zsh.yml

- name: Install rtx
  ansible.builtin.import_tasks: install-rtx.yml

- name: Install rtx utilities
  ansible.builtin.import_tasks: install-rtx-utilities.yml
