---
- name: Create "{{ ansible_username }}" group
  tags: ansible-setup
  ansible.builtin.group:
    name: "{{ ansible_username }}"

- name: Create "{{ ansible_username }}" user
  tags: ansible-setup
  ansible.builtin.user:
    name: "{{ ansible_username }}"
    group: "{{ ansible_username }}"
    groups: sudo
    system: true

- name: Copy "{{ ansible_username }}" user sudoers file
  tags: ansible-setup
  ansible.builtin.template:
    src: users/ansible/sudoer.j2
    dest: /etc/sudoers.d/"{{ ansible_username }}"
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s

- name: Set authorized key for "{{ ansible_username }}" user
  tags: ansible-setup
  ansible.posix.authorized_key:
    user: "{{ ansible_username }}"
    key: "{{ lookup('file', 'files/users/ansible/ssh/id-ed25519.pub') }}"

- name: Install ansible required packages
  tags: ansible-setup
  ansible.builtin.package:
    name: acl
