---
- name: Install chrony
  ansible.builtin.package:
    name: chrony

- name: Start chrony
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true

- name: Set timezone
  ansible.builtin.timezone:
    name: Europe/London
  notify: Restart chrony
