---
name: Build Main

"on":
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          persist-credentials: false

      - name: Release
        # yamllint disable-line rule:line-length
        uses: cycjimmy/semantic-release-action@3b88c82b34098e8b51e401c1082c9170b0a3ec3c # tag=v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: aki-bot[bot]
          GIT_AUTHOR_EMAIL: 103840025+aki-bot[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: aki-bot[bot]
          GIT_COMMITTER_EMAIL: 103840025+aki-bot[bot]@users.noreply.github.com
        with:
          # renovate: datasource=npm depName=semantic-release
          semantic_version: 19.0.2
          extra_plugins: conventional-changelog-conventionalcommits
