---
name: Build Main

"on":
  push:
    branches: [main]

env:
  # renovate: datasource=npm depName=@semantic-release/changelog
  SEMANTIC_RELEASE_CHANGELOG_VERSION: 6.0.3

  # renovate: datasource=npm depName=@semantic-release/git
  SEMANTIC_RELEASE_GIT_VERSION: 10.0.1

  # renovate: datasource=npm depName=conventional-changelog-conventionalcommits
  CONVENTIONAL_CHANGELOG_CONVENTIONALCOMMITS_VERSION: 6.1.0

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    with:
      continue-on-error: true

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    with:
      continue-on-error: true

  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency: ${{ github.workflow }}-release

    outputs:
      release-published: ${{ steps.release.outputs.new_release_published }}
      release-version: ${{ steps.release.outputs.new_release_version }}

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          persist-credentials: false

      - name: Release
        id: release
        # yamllint disable-line rule:line-length
        uses: cycjimmy/semantic-release-action@cb425203a562475bca039ba4dbf90c7f9ac790f4 # v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: aki-bot[bot]
          GIT_AUTHOR_EMAIL: 103840025+aki-bot[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: aki-bot[bot]
          GIT_COMMITTER_EMAIL: 103840025+aki-bot[bot]@users.noreply.github.com
        with:
          # renovate: datasource=npm depName=semantic-release
          semantic_version: 21.1.2
          extra_plugins:
            "@semantic-release/changelog@\
            ${{ env.SEMANTIC_RELEASE_CHANGELOG_VERSION }} \
            @semantic-release/git@\
            ${{ env.SEMANTIC_RELEASE_GIT_VERSION }} \
            conventional-changelog-conventionalcommits@\
            ${{ env.CONVENTIONAL_CHANGELOG_CONVENTIONALCOMMITS_VERSION }}"

  deploy-to-prod:
    name: Deploy to prod
    needs: release
    if: needs.release.outputs.release-published == 'true'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      version: v${{ needs.release.outputs.release-version }}
    secrets:
      ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
      ANSIBLE_VAULT_PASSWORD_PROD: ${{ secrets.ANSIBLE_VAULT_PASSWORD_PROD }}
