---
name: Deploy to Production

"on":
  workflow_call:
    inputs:
      version:
        type: string
        description: Deployment version
        required: true
    secrets:
      ANSIBLE_SSH_PRIVATE_KEY:
        description: The SSH private key used by Ansible
        required: true
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Deployment version
        required: true
      extra-ansible-options:
        description: Extra ansible-playbook options
        required: false

env:
  # renovate: datasource=pypi depName=ansible-core
  ANSIBLE_CORE_VERSION: 2.12.5

jobs:
  deploy-to-production:
    name: Deploy to production
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Set up Python
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6 # tag=v3.1.2
        with:
          # renovate: datasource=docker depName=python versioning=docker
          python-version: 3.10.4

      - name: Install ansible
        run: pip install ansible-core=="$ANSIBLE_CORE_VERSION"

      - name: Run playbook
        # yamllint disable-line rule:line-length
        uses: dawidd6/action-ansible-playbook@671974ed60e946e11964cb0c26e69caaa4b1f559 # tag=v2.5.0
        with:
          directory: ansible
          playbook: apply-configuration.yml
          requirements: requirements.yml
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          options: ${{ github.event.inputs.extra-ansible-options }}
