---
name: Deploy to Prod

"on":
  workflow_call:
    inputs:
      version:
        type: string
        description: Deployment version
        required: true
    secrets:
      ANSIBLE_SSH_PRIVATE_KEY:
        description: The SSH private key used by Ansible
        required: true
      ANSIBLE_VAULT_PASSWORD_PROD:
        description: The vault prod password used by Ansible
        required: true
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Deployment version
        required: true
      extra-ansible-options:
        description: Extra ansible-playbook options
        required: false

concurrency: ${{ github.workflow }}

env:
  # renovate: datasource=pypi depName=ansible-core
  ANSIBLE_CORE_VERSION: 2.13.5

jobs:
  deploy-to-prod:
    name: Deploy to prod
    runs-on: self-hosted
    environment: prod

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          ref: ${{ (github.event.inputs || inputs).version }}

      - name: Set up Python
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # tag=v4.3.0
        with:
          # renovate: datasource=docker depName=python versioning=docker
          python-version: 3.11.0

      - name: Install ansible
        run: pip install ansible-core=="$ANSIBLE_CORE_VERSION"

      - name: Run playbook
        # yamllint disable-line rule:line-length
        uses: dawidd6/action-ansible-playbook@5d970176ea4bfd99a3f5004d48e293fe0994eda1 # tag=v2.6.1
        with:
          directory: ansible
          playbook: apply-configuration.yml
          requirements: requirements.yml
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          options: >
            -vv
            ${{ github.event.inputs.extra-ansible-options }}
        env:
          ANSIBLE_VAULT_PASSWORD_PROD: |
            ${{ secrets.ANSIBLE_VAULT_PASSWORD_PROD }}
