---
name: Deploy to Prod

"on":
  workflow_call:
    inputs:
      version:
        type: string
        description: Deployment version
        required: true
    secrets:
      ANSIBLE_SSH_PRIVATE_KEY:
        description: The SSH private key used by Ansible
        required: true
      ANSIBLE_VAULT_PASSWORD_PROD:
        description: The vault prod password used by Ansible
        required: true
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Deployment version
        required: true
      extra-ansible-options:
        description: Extra ansible-playbook options
        required: false

concurrency: ${{ github.workflow }}

env:
  # renovate: datasource=pypi depName=ansible-core
  ANSIBLE_CORE_VERSION: 2.14.3

  # renovate: datasource=pypi depName=netaddr
  NETADDR_VERSION: 0.8.0

jobs:
  deploy-to-prod:
    name: Deploy to prod
    runs-on: self-hosted
    environment: prod

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: ${{ (github.event.inputs || inputs).version }}

      - name: Set up Python
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          # renovate: datasource=docker depName=python versioning=docker
          python-version: 3.11.2

      - name: Install ansible playbook packages
        run: >
          pip install
          ansible-core=="$ANSIBLE_CORE_VERSION"
          netaddr=="$NETADDR_VERSION"

      - name: Run playbook
        # yamllint disable-line rule:line-length
        uses: dawidd6/action-ansible-playbook@5d970176ea4bfd99a3f5004d48e293fe0994eda1 # tag=v2.6.1
        with:
          directory: ansible
          playbook: apply-configuration.yml
          requirements: requirements.yml
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          options: >
            -vv
            ${{ github.event.inputs.extra-ansible-options }}
        env:
          ANSIBLE_VAULT_PASSWORD_PROD: |
            ${{ secrets.ANSIBLE_VAULT_PASSWORD_PROD }}
