---
name: Deploy

"on":
  workflow_call:
    inputs:
      environment:
        type: string
        description: Deployment environment
        required: true
      version:
        type: string
        description: Deployment version
        required: true
    secrets:
      ANSIBLE_SSH_PRIVATE_KEY:
        description: The SSH private key used by Ansible
        required: true
      ANSIBLE_VAULT_PASSWORD_PROD:
        description: The vault prod password used by Ansible
        required: true
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Deployment environment
        required: true
      version:
        type: string
        description: Deployment version
        required: true
      extra-ansible-options:
        description: Extra ansible-playbook options
        required: false

concurrency:
  ${{ github.workflow }}-${{ (github.event.inputs || inputs).environment }}

env:
  # renovate: datasource=pypi depName=ansible-core
  ANSIBLE_CORE_VERSION: 2.17.0

  # renovate: datasource=pypi depName=netaddr
  NETADDR_VERSION: 1.3.0

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment: ${{ (github.event.inputs || inputs).environment }}

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{ (github.event.inputs || inputs).version }}

      - name: Set up Python
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          # renovate: datasource=docker depName=python versioning=docker
          python-version: 3.12.4

      - name: Install ansible playbook packages
        run: >
          pip install
          ansible-core=="$ANSIBLE_CORE_VERSION"
          netaddr=="$NETADDR_VERSION"

      - name: Run playbook
        # yamllint disable-line rule:line-length
        uses: dawidd6/action-ansible-playbook@c97d71562fcba83cc1ea0602d5a77013427f7571 # v2.8.0
        with:
          directory: ansible
          playbook: apply-configuration.yml
          requirements: requirements.yml
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          options: >
            -vv
            ${{ github.event.inputs.extra-ansible-options }}
        env:
          ANSIBLE_VAULT_PASSWORD_PROD: |
            ${{ secrets.ANSIBLE_VAULT_PASSWORD_PROD }}
