---
name: Deploy

"on":
  workflow_call:
    inputs:
      environment:
        type: string
        description: Deployment environment
        required: true
      version:
        type: string
        description: Deployment version
        required: true
    secrets:
      ANSIBLE_SSH_PRIVATE_KEY:
        description: The SSH private key used by Ansible
        required: true
      ANSIBLE_VAULT_PASSWORD_PROD:
        description: The vault prod password used by Ansible
        required: true
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Deployment environment
        required: true
      version:
        type: string
        description: Deployment version
        required: true
      extra-ansible-options:
        description: Extra ansible-playbook options
        required: false

concurrency:
  ${{ github.workflow }}-${{ (github.event.inputs || inputs).environment }}

env:
  # renovate: datasource=pypi depName=ansible-core
  ANSIBLE_CORE_VERSION: 2.15.4

  # renovate: datasource=pypi depName=netaddr
  NETADDR_VERSION: 0.8.0

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment: ${{ (github.event.inputs || inputs).environment }}

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: ${{ (github.event.inputs || inputs).version }}

      - name: Set up Python
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          # renovate: datasource=docker depName=python versioning=docker
          python-version: 3.11.5

      - name: Install ansible playbook packages
        run: >
          pip install
          ansible-core=="$ANSIBLE_CORE_VERSION"
          netaddr=="$NETADDR_VERSION"

      - name: Run playbook
        # yamllint disable-line rule:line-length
        uses: dawidd6/action-ansible-playbook@5d970176ea4bfd99a3f5004d48e293fe0994eda1 # tag=v2.6.1
        with:
          directory: ansible
          playbook: apply-configuration.yml
          requirements: requirements.yml
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          options: >
            -vv
            ${{ github.event.inputs.extra-ansible-options }}
        env:
          ANSIBLE_VAULT_PASSWORD_PROD: |
            ${{ secrets.ANSIBLE_VAULT_PASSWORD_PROD }}
