---
name: Lint

"on":
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          fetch-depth: 0

      - name: Setup just
        # yamllint disable-line rule:line-length
        uses: extractions/setup-just@aa5d15c144db4585980a44ebfdd2cf337c4f14cb # tag=v1.4.0
        with:
          # renovate: datasource=crate depName=just
          just-version: 1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Python
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@c4e89fac7e8767b327bbad6cb4d859eda999cf08 # tag=v4.1.0
        with:
          # renovate: datasource=docker depName=python versioning=docker
          python-version: 3.10.5
          cache: pip

      - name: Install dependencies
        run: just install

      - name: Lint
        # yamllint disable-line rule:line-length
        uses: github/super-linter/slim@2d64ac1c067c34beaf7d24cc12733cd46236f76e # tag=v4.9.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GENERATED_FILES: true
          IGNORE_GITIGNORED_FILES: true
          YAML_ERROR_ON_WARNING: true
          ANSIBLE_COLLECTIONS_PATH: |
            ansible/galaxy/collections:ansible/collections
          ANSIBLE_ROLES_PATH: ansible/galaxy/roles:ansible/roles
          FILTER_REGEX_EXCLUDE: .*ansible/.*vault\.yml
