---
name: Test

"on":
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: macos-10.15

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Setup just
        # yamllint disable-line rule:line-length
        uses: extractions/setup-just@aa5d15c144db4585980a44ebfdd2cf337c4f14cb # tag=v1.4.0
        with:
          # renovate: datasource=crate depName=just
          just-version: 1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Python
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@v3.1.2
        with:
          # renovate: datasource=docker depName=python versioning=docker
          python-version: 3.10.4
          cache: pip

      - name: Install dependencies
        run: just install

      - name: Cache Vagrant boxes
        uses: actions/cache@v3.0.2
        with:
          path: ~/.vagrant.d/boxes
          key: "${{ runner.os }}-\
            vagrant-\
            ${{ hashFiles('ansible/molecule/default/molecule.yml') }}"
          restore-keys: ${{ runner.os }}-vagrant-

      - name: Test
        run: just test
