---
name: Test

"on":
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: macos-12

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Setup just
        # yamllint disable-line rule:line-length
        uses: extractions/setup-just@aa5d15c144db4585980a44ebfdd2cf337c4f14cb # tag=v1.4.0
        with:
          # renovate: datasource=crate depName=just
          just-version: 1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Python
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@c4e89fac7e8767b327bbad6cb4d859eda999cf08 # tag=v4.1.0
        with:
          # renovate: datasource=docker depName=python versioning=docker
          python-version: 3.10.5
          cache: pip

      - name: Install dependencies
        run: just install

      - name: Cache Vagrant boxes
        # yamllint disable-line rule:line-length
        uses: actions/cache@0865c47f36e68161719c5b124609996bb5c40129 # tag=v3.0.5
        with:
          path: ~/.vagrant.d/boxes
          key: "${{ runner.os }}-\
            vagrant-\
            ${{ hashFiles('ansible/molecule/default/molecule.yml') }}"
          restore-keys: ${{ runner.os }}-vagrant-

      - name: Test
        run: just test
